### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Left4Dad** [MoeMod/CSMoE#44]
Hello, i have downloaded the v17 apk of csmoe. But when i enter a game, it crashes. I think its because some models or textures are not in the csbtem file. Can I ask where to download the latest and updated extra things that has been added in v17? Can you link them to me? I am trying to find it on this website but I failed. Anyone can help me link them?

**Comment by MoeMod** [comment]
You can download the new resources at https://github.com/MoeMod/CSMoE-GameDir
By the way, the gamedir is no longer csbtem but csmoe now.

**Comment by Left4Dad** [comment]
Can you give me a direct link to download?😅. I clicked on the link so many times and try to find the link to download resouces but could not find it. Sorry about my problem lol. Can u give me direct link to download the resources?

**Comment by MoeMod** [comment]
there is a green button named "Clone and download".
click it and select "download ZIP" and you will get the pack.

**Comment by MoeMod** [comment]
I think that crashing if missing resources is not intended action.
It should be fixed to run without those resources...

**Comment by Left4Dad** [comment]
Thank you. I had fixed it :)
I had some questions to ask you...

How to enable headname hud? What command should i use?
In zombie mode 3 for v17, there wasn't anything special. Its just the layout that look more nicer. The guns in supply boxes are still the same as the previous version. I thought you will add new guns in the game. For Humans, when the attack reaches 200%, does it really make us deal more damage to zombies?? And for Zombie,there is a fire Skull bar, when it reaches full, it does not do anything??? It only adds more hp right? And what does the slot 5,6 and 7 do? Its empty. Is it because u will add other features in those slots as well?

-By the way, Zombie mode 3 is almost impossible to win if we set the time to 4-5 minutes.

-Another suggestion, why you did not make the normal zombies easier to kill for zombie mode 1 and 3? They had too much health and its already difficult to kill them with m249 or m4a1. Thats why humans keep dying. This mode should be fair. Let the Master Zombie hard to kill, and the rest of normal zombies easier to kill...(just a suggestion)

For zombie scenario, can u add a boss battle every 10 rounds? Or make them walk faster when it reaches round 5? Because from round 1 to 15, its easy to kill the zombies because they have super low hp and they walk so slow and it take so so much time to even fight the zombies till they reach a harder level for example, lvl 22 and above. Than they will start running and have more hp. But this took so much time dont you think? I hope you do something about this. And also please make a new gamemmode for Zombie boss battle. Where there is only one Gigantic zombie and all humans try to kill it. If the zombie killed a human,the humans dies and dont let it transform to a zombie. If you can..try to make the zombie huge, has powers(optional), run a little bit fast(but dont let it catch up to human easily), and make it to have alot of Hp so that it tooks 2 to 3 minutes of shooting to kill the zombie boss.

Another thing is, can you make a yapb verison of the v17 apk for me? I know that no one wants to play with yapb, but I want to play with those bots. Can u make a custom apk for me that supports yapb??

-If I sounded rude, sorry btw. Thats how i usually type. I respect everything and the effort you had put in this game. Thank you for making this game fun. Oh btw, plz add Zombie Escape. The most fun zombie mode I had ever played!

**Comment by MoeMod** [comment]
> How to enable headname hud? What command should i use? 

cl_headname 1 to enable it. However, it can cause low fps so it's disabled by default.

> Its just the layout that look more nicer.

The morale and rage system just work not only on HUD. Human's attack should be increased. When the rage reaches 100%, you will get an evolution just as the one in ZB2.

> By the way, Zombie mode 3 is almost impossible to win if we set the time to 4-5 minutes.

Some features for human are not fully implemented, such as heroes. They will make it easier.

> For zombie scenario, can u add a boss battle every 10 rounds? Or make them walk faster when it reaches round 5?

Bosses in Zombie Scenario are planned, but not to be implements soon. I am sorry that I don't have much time. I will appreciate it if someone can do that.

> Another thing is, can you make a yapb verison of the v17 apk for me?

The current version of CSMoE is not compatible with YaPB. The mp has been modified a lot and they may not work any more. And our current ZBOT was modified to fit in zombie mode, they should perform well.

> plz add Zombie Escape

Zombie Escape was planned too. However, we found it impossible to play ZE with bots. Even if we make it, it may be just a exploring game that nobody is chasing you... The gameplay will only works with online players in a server. On the other hand, ZE maps in CS1.6 is just not so interesting as the ones in CSGO.

**Comment by Left4Dad** [comment]
Hi..Thanks for your reply. I understood some features will be implemented in the future :)

-Can you help me make a custom apk? I know ur able to edit Xash and turn it into csmoe. But do you think u can edit Cs16client on version 1.33 and 1.35? I want both apks. And i want to play with yapb bots with those two versions of apk and I am not sure if u must edit the xash or cs16client to make my request. Can you try to add these things if possible? 

1) when yapb bots die, they will drop grenade,rifle and pistol on the floor. The grenade was in one of your Original mode in csmoe where bots will drop their grenade from inv so that we can pick it up.

2) Can you make the yapb bots support mp_freeforall 1? I want to play deathmatch with yapb. I asked Jeefo/yapb to make this and he made some yapb files that ends with dylib,so,dll. He forgot to recompile the apk for me. Can u recompile the yapb files into the cs16client for me?? If u need files, u can ask me or go to his Yapb website on github aswell. Hope u can help me with this. Or u can teach me how to recompile it :)

3) Can u make the csgo type of scoreboard on the screen?? Just like the one from csmoe but I want it to look like csgo style of scoreboard. 

4) Nothing much...just to tell you if you really can do this private apk for me, i might even donate some money to you on paypal. Cuz i know these are hard to do. Tell me if you can do any of the above :D

**Comment by MoeMod** [comment]
1. Dropping grenades is maybe a bug in CSMoE. I remember that it should not happen, and it may need further testing.
2. You can compile it yourself with NDK r12b, Android SDK 19 (probably). It may need lots of fixes with headers because there are some differences between Android and PC systems.
3. We are not planning to make another HUD. In addition, I don't know how to extract images from CSGO.
4. I am sorry that I can't help you... I don't know much about YaPB, and maybe you can turn to the original repo for helps.
